const Images = {
  logo: new URL("./logo.png", import.meta.url).href,
  registerBG: new URL("./registerBG.png", import.meta.url).href,
  hero_1: new URL("./hero-img/hero-1.jpg", import.meta.url).href,
  hero_2: new URL("./hero-img/hero-2.jpg", import.meta.url).href,
  hero_3: new URL("./hero-img/hero-3.jpg", import.meta.url).href,
  hero_4: new URL("./hero-img/hero-4.jpg", import.meta.url).href,
  cat_1: new URL("./cat-img/cat-1.jpg", import.meta.url).href,
  cat_2: new URL("./cat-img/cat-2.jpg", import.meta.url).href,
  cat_3: new URL("./cat-img/cat-3.jpg", import.meta.url).href,
  cat_4: new URL("./cat-img/cat-4.jpg", import.meta.url).href,
  cat_5: new URL("./cat-img/cat-5.jpg", import.meta.url).href,
  cat_6: new URL("./cat-img/cat-6.jpg", import.meta.url).href,
  cat_7: new URL("./cat-img/cat-7.jpg", import.meta.url).href,
  cat_8: new URL("./cat-img/cat-8.jpg", import.meta.url).href,
  cat_9: new URL("./cat-img/cat-9.jpg", import.meta.url).href,
  cat_10: new URL("./cat-img/cat-10.jpg", import.meta.url).href,
  cat_11: new URL("./cat-img/cat-11.jpg", import.meta.url).href,
  cat_12: new URL("./cat-img/cat-12.jpg", import.meta.url).href,
};
export default Images;
